### ISSUE TITLE
STAT Documentation Preview Site Icons

### ISSUE THREAD

**Issue by sentientredstripe** [sentientredstripe/sentientredstripe.github.io#26]
![screenshot 2017-12-03 at 10 02 22 am](https://user-images.githubusercontent.com/11892238/33526547-281a9d8e-d811-11e7-8a15-2fa4013e68f3.png)

Don't think your new icons worked out exactly as planned @chris-sarli... probably something with the way the autogenerated stylesheets handle the icons something something.

Issue is that the icons appear blurry/out of focus.

**Comment by chris-sarli** [comment]
Really? It looks good on my end.

<img width="465" alt="screen shot 2017-12-03 at 10 08 22" src="https://user-images.githubusercontent.com/20889858/33526616-eeb3eba8-d811-11e7-9c23-d4d73320c662.png">

**Comment by sentientredstripe** [comment]
Might have something to do with scaling and/or device resolutions:

- Retina MacBook Pro: OK
- Chromebooks (720p @11.6 in.): Fuzzy at 100%
- Ian's PC (720p @ 15.6 in.): Fuzzy at 100% but OK at 170% (any higher and the CSS switches to mobile)
- Nexus 5X (1080p @ 5.2 in.): OK in both desktop and mobile mode.

If I can specify to show icons at 2x size *only* on low-res devices then maybe it will be OK?

**Comment by sentientredstripe** [comment]
Used new icons with switch to separate repo. Will have to test on a retina device though.  See https://github.com/sentientredstripe/stat-documents/commit/d1ef66180f10f50ede23e7ecc960caeee6626b42
